//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitydatakatrarim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SQLFULLEntities : DbContext
    {
        public SQLFULLEntities()
            : base("name=SQLFULLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<MusteriGirisBilgileri> MusteriGirisBilgileri { get; set; }
        public virtual DbSet<Ornek3> Ornek3 { get; set; }
        public virtual DbSet<Ornek4> Ornek4 { get; set; }
        public virtual DbSet<Satis> Satis { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Ornek1> Ornek1 { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<StudentAddress> StudentAddress { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_Musteri_YeniKayit(Nullable<int> iD, string isim, string soyisim, string email, string kullaniciAdi, string sifre, string gizliSoru, string cevap)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var isimParameter = isim != null ?
                new ObjectParameter("isim", isim) :
                new ObjectParameter("isim", typeof(string));
    
            var soyisimParameter = soyisim != null ?
                new ObjectParameter("soyisim", soyisim) :
                new ObjectParameter("soyisim", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var kullaniciAdiParameter = kullaniciAdi != null ?
                new ObjectParameter("kullaniciAdi", kullaniciAdi) :
                new ObjectParameter("kullaniciAdi", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("sifre", sifre) :
                new ObjectParameter("sifre", typeof(string));
    
            var gizliSoruParameter = gizliSoru != null ?
                new ObjectParameter("gizliSoru", gizliSoru) :
                new ObjectParameter("gizliSoru", typeof(string));
    
            var cevapParameter = cevap != null ?
                new ObjectParameter("cevap", cevap) :
                new ObjectParameter("cevap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Musteri_YeniKayit", iDParameter, isimParameter, soyisimParameter, emailParameter, kullaniciAdiParameter, sifreParameter, gizliSoruParameter, cevapParameter);
        }
    
        public virtual ObjectResult<string> sp_musteriisim(Nullable<int> musteriID)
        {
            var musteriIDParameter = musteriID.HasValue ?
                new ObjectParameter("MusteriID", musteriID) :
                new ObjectParameter("MusteriID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_musteriisim", musteriIDParameter);
        }
    
        public virtual int sp_musteriKayit(Nullable<int> musteriID, string isim, string soyisim)
        {
            var musteriIDParameter = musteriID.HasValue ?
                new ObjectParameter("MusteriID", musteriID) :
                new ObjectParameter("MusteriID", typeof(int));
    
            var isimParameter = isim != null ?
                new ObjectParameter("Isim", isim) :
                new ObjectParameter("Isim", typeof(string));
    
            var soyisimParameter = soyisim != null ?
                new ObjectParameter("Soyisim", soyisim) :
                new ObjectParameter("Soyisim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_musteriKayit", musteriIDParameter, isimParameter, soyisimParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_Satis_KayitDuzenle(Nullable<int> iD, Nullable<int> mID, Nullable<int> uID, Nullable<int> satilanAdet)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var mIDParameter = mID.HasValue ?
                new ObjectParameter("MID", mID) :
                new ObjectParameter("MID", typeof(int));
    
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            var satilanAdetParameter = satilanAdet.HasValue ?
                new ObjectParameter("SatilanAdet", satilanAdet) :
                new ObjectParameter("SatilanAdet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Satis_KayitDuzenle", iDParameter, mIDParameter, uIDParameter, satilanAdetParameter);
        }
    
        public virtual int SP_Satis_KayitSil(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Satis_KayitSil", iDParameter);
        }
    
        public virtual int SP_Satis_YeniKayit(Nullable<int> iD, Nullable<int> mID, Nullable<int> uID, Nullable<int> satilanAdet)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var mIDParameter = mID.HasValue ?
                new ObjectParameter("MID", mID) :
                new ObjectParameter("MID", typeof(int));
    
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            var satilanAdetParameter = satilanAdet.HasValue ?
                new ObjectParameter("SatilanAdet", satilanAdet) :
                new ObjectParameter("SatilanAdet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Satis_YeniKayit", iDParameter, mIDParameter, uIDParameter, satilanAdetParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SP_urun_kayitDuzenle(Nullable<int> urunID, string tanim, Nullable<int> adet)
        {
            var urunIDParameter = urunID.HasValue ?
                new ObjectParameter("UrunID", urunID) :
                new ObjectParameter("UrunID", typeof(int));
    
            var tanimParameter = tanim != null ?
                new ObjectParameter("Tanim", tanim) :
                new ObjectParameter("Tanim", typeof(string));
    
            var adetParameter = adet.HasValue ?
                new ObjectParameter("Adet", adet) :
                new ObjectParameter("Adet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_urun_kayitDuzenle", urunIDParameter, tanimParameter, adetParameter);
        }
    
        public virtual ObjectResult<SP_Urun_Listele_Result> SP_Urun_Listele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Urun_Listele_Result>("SP_Urun_Listele");
        }
    
        public virtual ObjectResult<SP_Urun_TekKayit_Result> SP_Urun_TekKayit(Nullable<int> urunID)
        {
            var urunIDParameter = urunID.HasValue ?
                new ObjectParameter("UrunID", urunID) :
                new ObjectParameter("UrunID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Urun_TekKayit_Result>("SP_Urun_TekKayit", urunIDParameter);
        }
    
        public virtual int SP_Urun_YeniKayit(Nullable<int> urunID, string tanim, Nullable<int> adet)
        {
            var urunIDParameter = urunID.HasValue ?
                new ObjectParameter("UrunID", urunID) :
                new ObjectParameter("UrunID", typeof(int));
    
            var tanimParameter = tanim != null ?
                new ObjectParameter("Tanim", tanim) :
                new ObjectParameter("Tanim", typeof(string));
    
            var adetParameter = adet.HasValue ?
                new ObjectParameter("Adet", adet) :
                new ObjectParameter("Adet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Urun_YeniKayit", urunIDParameter, tanimParameter, adetParameter);
        }
    }
}
