//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitydatakatrarim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int ID { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> olusturmaTarihi { get; set; }
    
        public virtual MusteriGirisBilgileri MusteriGirisBilgileri { get; set; }
    }
}
