//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitydatakatrarim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ornek4
    {
        public int ID { get; set; }
        public string ISim { get; set; }
        public string Soyisim { get; set; }
        public Nullable<int> Yas { get; set; }
    }
}
